// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	CategoryID       int64  `gorm:"column:CategoryID;type:int(11);primaryKey;autoIncrement:true" json:"CategoryID"` // 商品类别唯一标识符
	CategoryName     string `gorm:"column:CategoryName;type:varchar(255);not null" json:"CategoryName"`             // 商品类别的名称
	ParentCategoryID int64  `gorm:"column:ParentCategoryID;type:int(11)" json:"ParentCategoryID"`                   // 商品类别的父类别，用于建立类别的层次结构，可为空
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
