// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProduct = "product"

// Product mapped from table <product>
type Product struct {
	ProductID          int64     `gorm:"column:ProductID;type:int(11);primaryKey;autoIncrement:true" json:"ProductID"`             // 商品唯一标识符
	ProductName        string    `gorm:"column:ProductName;type:varchar(255);not null" json:"ProductName"`                         // 商品名称
	ProductDescription string    `gorm:"column:ProductDescription;type:text" json:"ProductDescription"`                            // 商品描述
	ProductPrice       float64   `gorm:"column:ProductPrice;type:decimal(10,2);not null" json:"ProductPrice"`                      // 商品价格，以十进制表示
	ProductImageURL    string    `gorm:"column:ProductImageURL;type:varchar(255)" json:"ProductImageURL"`                          // 商品图片的 URL
	ProductStock       int64     `gorm:"column:ProductStock;type:int(11);not null" json:"ProductStock"`                            // 商品库存数量
	CreationDate       time.Time `gorm:"column:CreationDate;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"CreationDate"` // 商品创建日期，默认为当前时间戳
	UpdateDate         time.Time `gorm:"column:UpdateDate;type:datetime;not null" json:"UpdateDate"`                               // 商品最后更新日期
	CategoryID         int64     `gorm:"column:CategoryID;type:int(11)" json:"CategoryID"`                                         // 商品所属类别的外键
	SellerID           int64     `gorm:"column:SellerID;type:int(11)" json:"SellerID"`                                             // 商品的卖家用户ID，外键指向用户表
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
