// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserID           int64     `gorm:"column:UserID;type:int(11);primaryKey;autoIncrement:true" json:"UserID"`                            // 用户唯一标识符
	Username         string    `gorm:"column:Username;type:varchar(50);not null" json:"Username"`                                         // 用户名，用于登录，必须唯一
	Password         string    `gorm:"column:Password;type:varchar(100);not null" json:"Password"`                                        // 用户密码，用于登录，存储的是加密后的密码
	Email            string    `gorm:"column:Email;type:varchar(100);not null" json:"Email"`                                              // 用户的电子邮件地址
	FullName         string    `gorm:"column:FullName;type:varchar(50)" json:"FullName"`                                                  // 用户的全名
	Address          string    `gorm:"column:Address;type:varchar(255)" json:"Address"`                                                   // 用户的地址
	PhoneNumber      string    `gorm:"column:PhoneNumber;type:varchar(20)" json:"PhoneNumber"`                                            // 用户的电话号码
	RegistrationDate time.Time `gorm:"column:RegistrationDate;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"RegistrationDate"` // 用户注册日期，默认为当前时间戳
	LastLoginTime    time.Time `gorm:"column:LastLoginTime;type:timestamp;not null" json:"LastLoginTime"`                                 // 用户最后登录时间
	UserRole         string    `gorm:"column:UserRole;type:enum('买家','商家');default:买家" json:"UserRole"`                                   // 用户角色，可以是 "买家" 或 "商家"，默认为 "买家"
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
